## NumPy Indexing and Selection

In [ ]:
import numpy as np

## Indexing on 1D Array

In [17]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
arr[8]

8

In [19]:
#Start from 0th index to 5th index
print(arr[0:5])
print(arr[:5])

[0 1 2 3 4]
[0 1 2 3 4]


In [20]:
#All the way to the end
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [21]:
#From beginning all the way to the end 
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
#Last item
arr[-1]

10

## Boardcasting

In [23]:
#Original Array
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
#you can change through index
#Boardcasting re-assignment
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

## Slicing

In [26]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
slice_of_arr = arr[0:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [30]:
slice_of_arr[:] = 99
print("Slice of array: ",slice_of_arr)
print("Original of array: ",arr)

Slice of array:  [99 99 99 99 99]
Original of array:  [99 99 99 99 99  5  6  7  8  9 10]


**Here The Boardcasting is afftected to the original array by slicing**

In [36]:
#if you don't want to afftected
#Then need to explicitly copy the original array
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [37]:
arr_copy[0:5] = 100
print("Slice of array: ",arr_copy)
print("Original of array: ",arr)

Slice of array:  [100 100 100 100 100   5   6   7   8   9  10]
Original of array:  [99 99 99 99 99  5  6  7  8  9 10]


## Indexing on 2D Array

In [39]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [40]:
arr_2d.shape

(3, 3)

### Signle item

In [42]:
#Signle item 25
#array[row,col]
#array[row][col]
print(arr_2d[1,1])
print(arr_2d[1][1])

25
25


In [43]:
#Signle item 15
print(arr_2d[0,2])
print(arr_2d[0][2])

15
15


### Multiple Items/Slicing

In [44]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [56]:
#10, 15
#25, 30
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [58]:
#25, 30
#40, 45
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [61]:
#25
#40
arr_2d[1: , 1:2 ]

array([[25],
       [40]])

## Conditional Selection

In [64]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [67]:
#Need items of true
bool_arr = arr > 4
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [68]:
#in one line
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])