## Numpy Operations

In [ ]:
import numpy as np

In [4]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### element by element basis operations

In [14]:
#element by element basis
add_arr = arr + 5
sub_arr = arr - 2
mult_arr = arr * 3
div_arr = arr / 4

print("Add with 5: ",add_arr)
print("Sub by 2 : ",sub_arr)
print("Multi by 3: ", mult_arr)
print("Div by 4: ", div_arr)

Add with 5:  [ 5  6  7  8  9 10 11 12 13 14]
Sub by 2 :  [-2 -1  0  1  2  3  4  5  6  7]
Multi by 3:  [ 0  3  6  9 12 15 18 21 24 27]
Div by 4:  [0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.   2.25]


In [15]:
arrAddarr= arr + arr
print("Add arr with arr: ", arrAddarr)

Add arr with arr:  [ 0  2  4  6  8 10 12 14 16 18]


In [16]:
arrSubarr= arr - arr
print("Sub arr with arr: ", arrSubarr)

Sub arr with arr:  [0 0 0 0 0 0 0 0 0 0]


In [17]:
#Divide by arr
arrDivarr= arr / arr
print("Div arr with arr: ", arrDivarr)

Div arr with arr:  [nan  1.  1.  1.  1.  1.  1.  1.  1.  1.]


E:\Anaconda Program Data\Program Data\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


**In Numpy, it gives 0/0 = nan which is [not a number]**

In [18]:
1 / arr

E:\Anaconda Program Data\Program Data\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

**In Numpy, it gives 1/0 = inf which is [infinity]**
### "So, keep in mind 'nan or inf' can be dangerous. Because it should error in general"

## Other operations

In [19]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [20]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [22]:
#Same warning for log(0)
np.log(arr)

E:\Anaconda Program Data\Program Data\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [23]:
arr.sum()

45

In [25]:
arr.mean()

4.5

In [26]:
arr.std()

2.8722813232690143

In [27]:
arr.var()

8.25

## Numpy operations with 2D Array

In [30]:
arr2d = np.arange(0, 25).reshape(5,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
arr2d.shape

(5, 5)

In [32]:
arr2d.sum()

300

### Sum by axis
    * axis=0 [row wise]
    * axis=1 [col wise]
    * it from (5,5) or (row, col) or (0, 1)

In [38]:
#Row wise sum
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [39]:
#Col wise sum
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])