## Numpy Array

In [ ]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
nasted_list = [[1,2],[3,4],[5,6]]

In [6]:
nasted_list

[[1, 2], [3, 4], [5, 6]]

In [9]:
#it will convert into 2D matrix (3,2)
np.array(nasted_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

### np.arange(...)

In [10]:
#start, stop
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
#start, stop, step
np.arange(0,11, 2)

array([ 0,  2,  4,  6,  8, 10])

### np.zeros(...)

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### np.ones(...)

In [17]:
np.ones(3)

array([1., 1., 1.])

In [19]:
np.ones((4,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### np.linspace(...)

In [25]:
#start, stop, num=50
np.linspace(0, 10, 21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

### np.eye(...) Diagonal matrix

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### np.random.rand(...)

In [27]:
np.random.rand(2)

array([0.05756017, 0.49346815])

In [30]:
np.random.rand(3,4)

array([[0.92032574, 0.98901937, 0.46260798, 0.08057212],
       [0.72283678, 0.2758496 , 0.12496663, 0.45877494],
       [0.26385947, 0.37721861, 0.83656109, 0.00854849]])

In [31]:
np.random.randn(3)

array([ 1.02047832,  0.69313274, -1.20149814])

In [33]:
np.random.randn(3,4)

array([[-0.52981002, -0.09110547,  0.81465816,  0.18856157],
       [-0.12950518,  0.95807715, -0.04431648,  0.26344963],
       [-0.25350125,  0.12852923, -1.29248417, -0.68231137]])

In [34]:
np.random.randint(3)

2

In [38]:
#low, high
np.random.randint(1,10)

7

In [39]:
#low, high, size
np.random.randint(1,10, (3,4))

array([[2, 8, 8, 2],
       [6, 5, 1, 5],
       [1, 1, 6, 4]])

### np.random.seed(...)

**Note: Try to make sure np.random.seed(42) and np.random.rand(4) in the same cell.**

In [41]:
# .seed() will give same random number in different environment
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [44]:
np.random.rand(4)

array([0.60111501, 0.70807258, 0.02058449, 0.96990985])

### array.shape and array.reshape

In [47]:
arr = np.arange(25)
rand_arr = np.random.randint(0, 50, 10)

In [51]:
print('Values: ',arr)
print('Shape: ',arr.shape)

Values:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
Shape:  (25,)


In [52]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**But no change in original array**

In [53]:
print('Values: ',arr)

Values:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


### max(), argmax(), min(), mean(), sum(),

In [55]:
print('Values: ',rand_arr)

Values:  [ 6 20  8 38 17  3 24 13 49  8]


In [56]:
rand_arr.max()

49

In [64]:
#index/location of max value
print("index of max value:",rand_arr.argmax())

index of max value: 8


In [57]:
rand_arr.min()

3

In [65]:
#index/location of min value
print("index of max value:",rand_arr.argmin())

index of max value: 5


In [58]:
rand_arr.mean()

18.6

In [60]:
rand_arr.sum()

186

### array.dtype

In [66]:
rand_arr.dtype

dtype('int32')